name: "Default Deploy"
description: "Builds and Deploys to specified environment"
inputs:
  wp-env:
    required: true
    description: ""
  theme:
    description: theme directory
    required: true
  env_domain:
    required: true
    description: ""
  env_root_domain:
    required: true
    description: ""
  project_root_domain:
    required: true
    description: ""
  env_subdomain:
    required: true
    description: ""
    default: ""
  acf_licence_key:
    required: true
    description: ""
  ac_token:
    required: true
    description: ""
  yoast_seo_token:
    description: ""
  dev_only_plugins:
    required: true
    description: ""
  ssh-user:
    description: "SSH user to use"
    required: true
  ssh-host:
    description: "SSH host to use"
    required: true
  ssh-port:
    description: "SSH port to use"
    required: false
    default: "22"
  ssh-key:
    description: "SSH key to add"
    required: true
  db_name:
    required: true
    description: ""
  db_user:
    required: true
    description: ""
  db_password:
    required: true
    description: ""
  db_prefix:
    required: true
    description: ""
  wp_cache_key_salt:
    required: true
    description: ""
  wp_redis_database:
    required: true
    description: ""
  destination-path:
    required: true
    description: ""
  crm_application_password:
    description: ""
    default: ""
  falo_api_password:
    description: ""
    default: ""
  compile:
    description: ""
    default: "yes"

runs:
  using: "composite"
  steps:
    - name: Checkout and Verify Branch is up to date
      uses: atticusseven/.github/actions/checkout-and-verify@main

    - name: Compile, Minify and Combine
      if: "${{ inputs.compile == 'yes'  }}"
      uses: atticusseven/.github/actions/compile-minify-combine@main
      with:
        theme_dir: html/content/themes/${{ inputs.theme }}

    - name: Install Composer Dependencies
      uses: atticusseven/.github/actions/install-composer-dependencies@main
      with:
        env_domain: ${{ inputs.env_domain }}
        acf_licence_key: ${{ inputs.acf_licence_key }}
        ac_token: ${{ inputs.ac_token }}
        yoast_seo_token: ${{ inputs.yoast_seo_token }}
        env: ${{ inputs.wp-env }}
        dev_only_plugins: ${{ inputs.dev_only_plugins }}

    # - name: Debug
    #   run: ls -la html/content/mu-plugins/admin-columns-pro/assets
    #   shell: bash

    - name: Add SSH Key to this runner
      uses: atticusseven/.github/actions/add-ssh-key@main
      with:
        ssh-user: ${{ inputs.ssh-user }}
        ssh-port: ${{ inputs.ssh-port }}
        ssh-host: ${{ inputs.ssh-host }}
        ssh-key: ${{ inputs.ssh-key }}

    - name: Create .env from template.env
      uses: atticusseven/.github/actions/setup-env@main
      with:
        db_name: ${{ inputs.db_name }}
        db_user: ${{ inputs.db_user }}
        db_password: ${{ inputs.db_password }}
        db_prefix: ${{ inputs.db_prefix }}
        wp_cache_key_salt: ${{ inputs.wp_cache_key_salt }}
        wp_redis_database: ${{ inputs.wp_redis_database }}
        crm_application_password: ${{ inputs.crm_application_password }}
        falo_api_password: ${{ inputs.falo_api_password }}
        env_domain: ${{ inputs.env_domain }}
        env_root_domain: ${{ inputs.env_root_domain }}
        project_root_domain: ${{ inputs.project_root_domain }}
        env_subdomain: ${{ inputs.env_subdomain }}

        #network_ip:

    - name: RSync to the Server
      uses: atticusseven/.github/actions/deploy-via-rsync@main
      with:
        destination-path: ${{ inputs.destination-path }}

    - name: Check file existence
      id: check_files
      uses: andstor/file-existence-action@v3
      with:
        files: "premium-plugins"

    - name: Install Premium Plugins
      if: steps.check_files.outputs.files_exists == 'true'
      uses: atticusseven/.github/actions/install-premium-plugins@main
      with:
        destination-path: ${{ inputs.destination-path }}

    - name: WP Cleanup
      uses: atticusseven/.github/actions/wp-cleanup@main
      with:
        destination-path: ${{ inputs.destination-path }}

    - name: Make Live
      uses: atticusseven/.github/actions/make-live@main
      with:
        destination-path: ${{ inputs.destination-path }}
        env: ${{ inputs.wp-env }}
