name: Install Composer Dependencies
description: Run composer install to install Wordpress and and other dependencies. Insert tokens from repo inputs required for premium dependencies
inputs:
  root_dir:
    description: location of the site root directory
    required: true
    default: html
  env_domain:
    description: the website's URL
    required: true
  acf_licence_key:
    description: ACF Pro Licence Key
    required: true
  ac_token:
    description: Admin Columns Pro token
    required: true
  yoast_seo_token:
    description: Yoast SEO Premium token
    required: true
  env:
    description: dev, staging, production
    required: true
  dev_only_plugins:
    description: json of plugins only used in dev
    required: true

runs:
  using: composite
  steps:
    - name: Edit composer.json and remove plugins if dev
      if: "${{ inputs.env != 'dev' }}"
      uses: atticusseven/.github/actions/delete-dev-only-plugins@main
      with:
        dev_only_plugins: ${{inputs.dev_only_plugins}}

    - name: Create auth.json
      if: "${{ inputs.acf_licence_key != '' && inputs.ac_token != '' }}"
      uses: atticusseven/.github/actions/create-auth-json@main
      with:
        acf_licence_key: ${{inputs.acf_licence_key}}
        ac_token: ${{inputs.ac_token}}
        env_domain: https://${{inputs.env_domain}}
    - name: Output auth.json
      run: cat ${{github.workspace}}/html/auth.json
      shell: bash
    - name: Register Yoast SEO token with composer
      if: "${{ inputs.yoast_seo_token != '' }}"
      run: composer config -g http-basic.my.yoast.com token ${{ inputs.yoast_seo_token }}
      shell: bash
    - name: Install composer dependencies
      uses: ramsey/composer-install@v2
      with:
        working-directory: ${{github.workspace}}/html
