name: "Deploy via Rsync"
description: ""
inputs:
  destination-path:
    description: "Destination path to copy files"
    required: true
  conf_dir:
    description: Path to the conf dir
    required: true
    default: conf

runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: Switch on maintenance mode
      run: switch-on-maintenance.sh ${{inputs.conf_dir}} ${{inputs.destination-path}}
      shell: bash
    - name: Rsync to the remote
      run: rsync -avPC --no-perms --delete --include 'core' --exclude-from='${{github.workspace}}/exclude.txt' . server:${{inputs.destination-path}}
      shell: bash
