name: "Default Deploy"
description: "Builds and Deploys to specified environment"
inputs:
  env:  
    description: "The environment to deploy to"
    required: true
    default: "production"
  ssh-user:
    description: "SSH user to use"
    required: true
  ssh-host:
    description: "SSH host to use"
    required: true
  ssh-port:
    description: "SSH port to use"
    required: false
    default: "22"
  ssh-key:
    description: "SSH key to add"
    required: true
  destination-path:
    description: Path to public_html on the web server
    required: true
  wp-theme:
    description: The directory name of the WordPress Theme
    required: true
  auth-json:
    description: Contains authentication for paid plugins to be installed using composer
    required: true
runs:
  using: "composite"
  steps:
    - name: Git checkout
      uses: actions/checkout@v3
    - name: Add HTTP basic auth credentials and .env file
      run: |
        echo '${{inputs.auth-json}}' > $GITHUB_WORKSPACE/auth.json
        echo '${{inputs.dot-env}}' > $GITHUB_WORKSPACE/.env
      shell: bash
    - name: Install composer dependencies at root
      uses: ramsey/composer-install@v3
    - name: Install composer dependencies in theme
      uses: ramsey/composer-install@v3
      with:
        working-directory: "wp-content/themes/${{inputs.wp-theme}}"
    - name: Remove unnecessary files
      run: |
        rm wp-content/themes/${{inputs.wp-theme}}/composer.json
        if [ "${{inputs.wp-theme}}" != "aseven-notheme" ]; then 
          rm wp-content/themes/${{inputs.wp-theme}}/package.json
          rm wp-content/themes/${{inputs.wp-theme}}/src/input.css
        fi 
      shell: bash
    - name: Add SSH Key to this runner
      uses: atticusseven/.github/actions/add-ssh-key@main
      with:
        ssh-user: ${{ inputs.ssh-user }}
        ssh-port: ${{ inputs.ssh-port }}
        ssh-host: ${{ inputs.ssh-host }}
        ssh-key: ${{ inputs.ssh-key }}
    - name: Rsync to the remote
      run: rsync -avPC --delete --no-perms --include-from='.rsyncinclude' --exclude-from='.rsyncignore' . server:${{inputs.destination-path}}
      shell: bash
    - name: Install WP-CLI
      run: |
        curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        chmod +x wp-cli.phar
        sudo mv wp-cli.phar /usr/local/bin/wp
        wp --info
      shell: bash
    - name: Activate production plugins
      if: "${{ inputs.env == 'production' }}"
      run: wp plugin activate --exclude=password-protected,disable-emails --all --ssh=server:${{ inputs.destination-path }}
      shell: bash
    - name: Activate dev/staging plugins
      if: "${{ inputs.env == 'dev' || inputs.env == 'staging' }}"
      run: wp plugin activate --exclude=updraftplus --all --ssh=server:${{ inputs.destination-path }}
      shell: bash
    - name: Update Database
      run: wp core update-db --ssh=server:${{ inputs.destination-path }}
      shell: bash
    - name: Flush Cache and Rewrites
      run: |
        wp cache flush --skip-plugins --skip-themes --ssh=server:${{ inputs.destination-path }}
        wp sg purge --skip-plugins --skip-themes --ssh=server:${{ inputs.destination-path }}
        wp rewrite flush --skip-plugins --skip-themes --ssh=server:${{ inputs.destination-path }}
      shell: bash
