name: "Collect Plugins"
description: "Scan all plugins, categories by 'free', 'premium', 'custom' and 'composer' and output a json file"
inputs:
  workspace:
    description: "Path to the Github Workspace / repo root"
    default: ${{github.workspace}}
  json_filename:
    description: "The name of the json file that will be output"
    default: "plugins.json"

runs:
  using: "node20"
  main: "index.js"
