name: Set Up
description: Installs and configure any packages required for deployment

runs:
  using: composite
  steps:
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 20
    - name: Install actions
      run: |
        npm i @actions/core
        npm i @actions/github
        ls -la
      shell: bash
    - name: Install PostCSS, PostCSS CLI and Autoprefixer
      run: npm i -D --global postcss postcss-cli autoprefixer
      shell: bash
    - name: Install json (npm package)
      run: npm install -g json
      shell: bash
    - name: Install jq (for bash)
      run: sudo apt-get install jq
      shell: bash
    - name: Install WP-CLI
      run: |
        curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        chmod +x wp-cli.phar
        sudo mv wp-cli.phar /usr/local/bin/wp
        wp --info
      shell: bash
